# Numerical python library(NumPy)

In [2]:
# you will recall that we import a library using 'import' keyword as numpy's common abbrivation is np
import numpy as np
import math

## Array creation

In [4]:
# array are displayed as a list or list of list and can be created througa list as well. wen creating an
# array we pass in alist as an agument in numpy arr
a = np.array([1,2,3])
print(a)
# we can print the number of dimensions of a list using ndim atribute
print(a.ndim)

[1 2 3]
1


In [6]:
# if we pass in a list of lists in numpy array, we create a multi-dimentional array, for instance, a matrix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# we can print out the length of each dimension by calling the shape attribute, which returns a tuple 
b.shape

(2, 3)

In [8]:
# we can also check the type of item in the array
a.dtype

dtype('int32')

In [9]:
# Besides integers, floats are also accepted in numpy arrays
c = np.array([2.2,5,1.1])
c.dtype.name

'float64'

In [10]:
# let's look at the data in our array
c

array([2.2, 5. , 1.1])

In [12]:
# note that numpy automatically convert integers, like 5 up to floats,sins there is no loss of prescision.
# numpy will try to give you the best data type format possible to keep your data types homogeneous, which
# menas all the same, in the array 

In [13]:
# sometimes we know the shape of an array that we want to create, but not what we want to be in it. 
# numpy offers several functions to create arrays with initial placeholders, such as zero's or one's.
# lets create two arrays, both the same shape but with different filler values 
d = np.zeros((2,3))
print(d)
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# we can also generate an array with random numbers
np.random.rand(2,3)

array([[0.41696387, 0.53702322, 0.4030148 ],
       [0.73127019, 0.39142134, 0.93501106]])

In [15]:
# you will see zeros, ones, and rand used quite often to create example arrays, especially in stack overflow 
# posts and other forues.

In [16]:
# we can also create a sequenceof numbers in an array with the arrange() function. 
# the fist argument is the starting bound and the second argument is the ending bound, and the third argument is the 
# difference between each consecutive numders 

# let,s create an array of every even numders from ten (inclusive) to fifty (exclusive)
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [17]:
# if we want to generate a sequence of floats, we can use the linspace() fuction. in this function the third agument isn't
# the difference between two numbers , but is the total number of items you want to generate 
np.linspace(0,2,15) # what it means is 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array operations

In [18]:
# we can do many things on arrays. such as mathematical manipulation (addition, subtraction, square, exponentes) as well 
# as use boolean arrays, which are binary valuse. we can also matrix manipulation such as product, transpose, inverse. and 
# so foth. 


In [19]:
# Aritmetic operators on array apply elementwise.
# let's creat a couple of arrays
a = np.array([10,20,30,40])
b = np.array([1,2,3,4,])

# now let's look at a minus b
c = a-b
print(c)

# and let's look at a times b
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [ ]:
# with arithmetic manipulation, we can convert current data to the way we want it to be. here's a real-world problem 
# that meany people face - in the united states they use faraheit temperatures, and like canader use's celcius for temperatures.
